# Generated by Django 5.1.2 on 2025-05-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ABOUT MAIYEMBE', max_length=200)),
                ('main_content', models.TextField(help_text='Main introduction paragraph')),
                ('secondary_content', models.TextField(help_text='Team experience paragraph')),
                ('additional_content', models.TextField(help_text='Project approach paragraph')),
                ('image', models.ImageField(help_text='About section image', upload_to='about/')),
                ('button_text', models.CharField(default='MEET OUR TEAM', max_length=50)),
                ('button_url', models.CharField(default='#team', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
    ]
