# Generated by Django 5.1.2 on 2025-08-02 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Starting price for this service', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Large hero image for service detail page', null=True, upload_to='services/featured/'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description',
            field=models.TextField(blank=True, help_text='Detailed description for service page', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='lead_time',
            field=models.CharField(blank=True, help_text="E.g. '4-12 weeks'", max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which services appear in listings'),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_description',
            field=models.CharField(blank=True, help_text="E.g. 'From $5,000' or 'Custom quotes available'", max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='process_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='process_title',
            field=models.CharField(blank=True, default='Our Process', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, help_text='Brief description for cards and listings', null=True),
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome icon class (e.g. 'fas fa-home')", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RelatedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('primary_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_relations', to='core.service')),
                ('related_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_relations', to='core.service')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('primary_service', 'related_service')},
            },
        ),
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='core.service')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('service', 'step_number')},
            },
        ),
    ]
