# Generated by Django 5.1.2 on 2025-08-08 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_service_options_remove_service_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicegalleryimage',
            name='service',
        ),
        migrations.AlterUniqueTogether(
            name='serviceprocessstep',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='serviceprocessstep',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='servicefeature',
            options={},
        ),
        migrations.RemoveField(
            model_name='service',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='lead_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.RemoveField(
            model_name='service',
            name='pricing_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='process_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='process_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='servicefeature',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='servicefeature',
            name='order',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('design', 'Design & Planning'), ('construction', 'Construction'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('management', 'Property Management'), ('other', 'Other Services')], default='construction', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g. 'fas fa-home')", max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='icon',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g. 'fas fa-check')", max_length=50),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('general', 'General Inquiry'), ('design', 'Design Consultation'), ('construction', 'Construction Project'), ('electrical', 'Electrical Work'), ('plumbing', 'Plumbing Work'), ('management', 'Property Management'), ('other', 'Other')], default='general', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('contact_method', models.CharField(choices=[('phone', 'Phone Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('in-person', 'In-Person Meeting')], default='whatsapp', max_length=50)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='RelatedService',
        ),
        migrations.DeleteModel(
            name='ServiceGalleryImage',
        ),
        migrations.DeleteModel(
            name='ServiceProcessStep',
        ),
    ]
