# Generated by Django 5.1.2 on 2025-08-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_servicegalleryimage_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
