# Generated by Django 5.1.2 on 2025-11-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_servicerequest_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_price_negotiable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="service",
            name="price_description",
            field=models.TextField(
                blank=True,
                help_text="Description of what's included in the starting price",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="price_display_type",
            field=models.CharField(
                choices=[
                    ("starting_from", "Starting From"),
                    ("fixed", "Fixed Price"),
                    ("custom", "Custom Quote"),
                ],
                default="starting_from",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="price_unit",
            field=models.CharField(
                blank=True,
                help_text="e.g., per square meter, per project, etc.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="starting_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Starting price for this service",
                max_digits=12,
                null=True,
            ),
        ),
    ]
