# Generated by Django 5.1.2 on 2025-11-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_service_is_price_negotiable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="estimated_duration",
            field=models.CharField(
                blank=True, help_text="e.g., 2-4 weeks, 1-2 days, etc.", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="includes_services",
            field=models.TextField(
                blank=True, help_text="List of services included (one per line)"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="optional_addons",
            field=models.TextField(
                blank=True,
                help_text="Optional additional services with prices (one per line)",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="pricing_breakdown",
            field=models.TextField(
                blank=True,
                help_text="Detailed breakdown of what's included in the price (one per line)",
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="budget_range",
            field=models.CharField(
                choices=[
                    ("under_10k", "Under ZMW 10,000"),
                    ("10k_50k", "ZMW 10,000 - 50,000"),
                    ("50k_100k", "ZMW 50,000 - 100,000"),
                    ("100k_250k", "ZMW 100,000 - 250,000"),
                    ("250k_500k", "ZMW 250,000 - 500,000"),
                    ("500k_1m", "ZMW 500,000 - 1,000,000"),
                    ("over_1m", "Over ZMW 1,000,000"),
                    ("custom", "Custom Budget"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="custom_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Specific budget amount if custom range selected",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="project_location",
            field=models.CharField(
                blank=True, help_text="Where is the project located?", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="project_timeline",
            field=models.CharField(
                blank=True,
                help_text="Desired timeline for project completion",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="price_display_type",
            field=models.CharField(
                choices=[
                    ("starting_from", "Starting From"),
                    ("fixed", "Fixed Price"),
                    ("custom", "Custom Quote"),
                    ("free_consultation", "Free Consultation"),
                ],
                default="starting_from",
                max_length=20,
            ),
        ),
    ]
