# Generated by Django 5.1.2 on 2025-11-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_newslettersubscriber_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_published",
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
    ]
